language: generic
git:
  depth: 1
branches:
  only:
    - master
script:
  - make docker-release
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_KEY
  bucket: ferret-lang.org
  skip_cleanup: true
  local-dir: release
  acl: public_read
  detect_encoding: true
notifications:
  email:
    on_success: never
    on_failure: always
