language: generic
git:
  depth: 1
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get build-dep emacs
  - wget http://ftp.gnu.org/gnu/emacs/emacs-24.5.tar.gz
  - tar xf emacs-24.5.tar.gz
  - cd emacs-24.5
  - ./configure
  - make
  - sudo make install
  - cd ../
  - sudo apt-get install -qq g++-5 leiningen
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50
  - ./build
script:
  - cd src/
  - lein test
  - cd ../
  - mkdir build
  - mv ferret build/
  - mv src/ferret.jar build/
deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_KEY
  bucket: dropbox.nakkaya.com
  skip_cleanup: true
  upload-dir: builds
  local-dir: build
  acl: public_read
  detect_encoding: true
notifications:
  email:
    on_success: never
    on_failure: always