language: generic
git:
  depth: 1
branches:
  only:
    - master
before_install:
  # Install Compiler Toolchains
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test > /dev/null 2>&1
  - sudo add-apt-repository -y ppa:h-rayflood/llvm > /dev/null 2>&1
  - sudo apt-get update -qq
  - sudo apt-get -qq -y build-dep emacs > /dev/null 2>&1
  - sudo apt-get install --allow-unauthenticated -y -qq g++-5 clang-3.4 cppcheck  > /dev/null 2>&1
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50
  # Install Emacs
  - wget -q http://ftp.gnu.org/gnu/emacs/emacs-24.5.tar.gz
  - tar xf emacs-24.5.tar.gz
  - cd emacs-24.5
  - ./configure > /dev/null 2>&1
  - make > /dev/null 2>&1
  - sudo make install > /dev/null 2>&1
  - cd ../
  # Install Clojure Toolchain
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - chmod +x lein
  - sudo mv lein /usr/bin/
  - lein
script:
  # Build and Test Ferret
  - ./build > /dev/null
  - cd src/
  - lein test
  # Prepare Platform Releases
  - bash resources/platform_builds.sh
  - cd ../
  - mkdir release
  - mkdir release/builds/
  # Move Packages to builds/
  - mv ferret release/builds/
  - cp src/target/ferret.jar release/builds/ferret-`git rev-parse --short HEAD`.jar
  - mv src/target/ferret.jar release/builds/
  - mv src/ferret-linux-amd64.zip release/builds/
  - mv src/ferret-macosx-x86_64.zip release/builds/
  - mv src/ferret-windows-amd64.zip release/builds/
  - mv ferret-manual.html release/index.html
  - mv org-mode-assets release/ferret-styles
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_KEY
  bucket: ferret-lang.org
  skip_cleanup: true
  local-dir: release
  acl: public_read
  detect_encoding: true
notifications:
  email:
    on_success: never
    on_failure: always
